### ISSUE TITLE
Votronic_VCC_1212 Baudrate

### ISSUE THREAD

**Issue by wolfgangmauer** [schroeder-robert/vantelligence_connector#3]
Hat tatsächlich jemand den Votronic_VCC_1212 am laufen?
Die Baudrate von 1000 kann doch nicht stimmen, oder?

> sudo setserial /dev/ttyS0 baud_base 1000 
> Cannot set serial info: Invalid argument

> stty -F /dev/ttyS0 1000
> stty: invalid argument ‘1000’

THX

**Comment by schroeder-robert** [comment]
Es sind tatsächlich genau 1000. Ich habe es mehrfach getestet, weil ich es selbst kaum glauben konnte.
Aber es hat nicht mit jedem Adapter funktioniert. Ein FTDI232-basierter hat funktioniert, jedoch ein PL2303-basierter nicht.
Mit dem Pi direkt habe ich es noch nicht versucht.

**Comment by wolfgangmauer** [comment]
Ich werde mal diese ausprobieren [https://www.amazon.de/dp/B0753GY7FR](https://www.amazon.de/dp/B0753GY7FR) ...

**Comment by schroeder-robert** [comment]
Genau die verwende ich auch.
