### ISSUE TITLE
Other Ective devices using serial port

### ISSUE THREAD

**Issue by TKone7** [schroeder-robert/vantelligence_connector#7]
Hey @schroeder-robert 
Thanks a lot for the awesome work. So far everything worked just flawlessly and integration into HA went like a breeze.

I also use a MPPT solar charger (ECTIVE SC 40) that uses the same port for the Bluetooth transmitter as does the DSC you integrated. However if I connect it to my computer (or a Raspberry) it does not even detect it as a USB device. Is it possible that my device works differently, or did I do something wrong?

Would be really appreciated if you would have some tips where I could start debugging.

Thanks a lot.

**Comment by schroeder-robert** [comment]
Thank you @TKone7!

What kind of serial to usb adaptor are you using?

**Comment by TKone7** [comment]
Thanks for the quick reply.

I was already using the official BLE adapter from Ective. I now just chopped off the Bluetooth dongle and connected GND, RX and TX to a USB-B plug. That is supposed to work like that, no?

**Comment by schroeder-robert** [comment]
No! That way you can damage your system or your charger!

The charger has an serial/uart connection. To connect it to a computer (or a Pi) you have to use a serial port on the computer's side. If there is none, you can use a serial to usb adator like this one: https://www.amazon.de/DTech-Seriell-Adapter-FT232RL-Windows/dp/B08L6B6XHN

**Comment by TKone7** [comment]
Oh woow, that explains a lot 😆  I guess I was mislead by the similarities between them (RX, TX) and just assumed that's the same.

I still got[ this one at home](https://www.amazon.de/-/en/gp/product/B0773G2K92/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&psc=1) from flashing my NS Panel. I guess that does the trick, no?

Thanks a lot for clarifying.

**Comment by schroeder-robert** [comment]
You can try that adaptor. I'm not sure about the CP2102 chipset that is used by your adaptor. I prefer FTDI chipsets. But chances are good that it will work.

**Comment by TKone7** [comment]
It works 🎉  You are amazing. Thanks a lot.

Today I learned an important lesson 😆
